### ISSUE TITLE
Problem with Bundle (Adam Mazel)

### ISSUE THREAD

**Issue by amaze2** [CollectionBuilder/dhsi-demo#9]
Dear Devin, Evan, and Olivia,
First, please ignore this issue if it is outside the bounds of this class (and my apologies if it is). 

But I'm having an issue with setting up my development server, in particular with the `bundle install` step: my bash terminal returns `Could not locate Gemfile` though I have successfully installed bundler with `gem install jekyll bundler`; when I enter `bundle list` it returns `Could not locate Gemfile or .bundle/ directory.` My ruby version is ruby 3.0.1p64 and when I enter `gem list` it returns `bundler (2.2.19, default: 2.2.15)`.

The reason I fear this question is outside the bounds of this class is that while I've gotten bundle to work in my dhsi-demo folder, this issue is related to applying what you've taught me to non-CollectionBuilder files. So I understand if you can't help with this!

Thank you either way!

**Comment by dcnb** [comment]
Hey Adam,

At the root of your dhsi-demo repository, you will have a file that is
simply named "Gemfile" -- simply copy and paste that file into your new
repository, do the bundle update command, and that should clear up the
problem. (This will also create a new file in your repo called Gemfile.lock
-- this is good)

If you're still having issues, we can fix this at the beginning of class.
And it's totally not out of bounds! We want this work to influence other
work you do!

Thinking about this, and some issues I had the last two days, maybe we
should explain those Gemfile Gemfile.lock files in more detail today ...

-Devin

**Comment by amaze2** [comment]
Hi Devin,
Thank you so much! This solved my issue perfectly. I really appreciate your taking the time to help with this! Thank you for solving this!!

And it would definitely benefit me to be taught / learn more about Gemfile & Gemfile.lock!

Thank you!
Adam
